name: auto-test

on:
  push:
    branches: [ test_action ]
  pull_request:
    branches: [ test_action ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Docker Build
        run: docker-compose build && docker-compose up -d
        