name: auto-test

on:
  push:
    branches: [ test_action ]
  pull_request:
    branches: [ test_action ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure local json
      run: >
        cat local_json_template.json |
        sed 's/\$DATABASE\$/yppf/g' |
        sed 's/\$USER\$/root/g' |
        sed 's/\$PASSWORD\$/secret/g' >
        local_json.json
          cat local_json.json

    - name: Start containers
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
    
    - name: Test 
      run: |
        sleep 5
        docker-compose logs yppf

